Changed behaviour in order to take arguments to command

diff --git a/bin/xdockrun b/bin/xdockrun
--- a/bin/xdockrun
+++ b/bin/xdockrun
@@ -1,21 +1,46 @@
 #!/bin/bash
+set -x
 
-if [ $# -ne 0 ]
+if [ $# -eq 0 ]
 then
-  containername=$@
-else
-  echo "Please specify a container name!"
-  echo "  $0 containername"
+  echo "Please specify a command to run!"
+  echo "  $0 command [arguments]"
   exit 1
 fi
 
+dateStr=$(date +%Y-%m-%d_%H:%M)
+
+containername=dockrun-$1
+imagename=$containername-image
+app=$1
+arguments="${@:2}"
+
+dfiledir=$HOME/.dockrun/$imagename-$dateStr
+dfile=$dfiledir/Dockerfile
+mkdir -p $dfiledir
+
 # Check if container exists
-docker container ps --all |grep $containername > /dev/null
-if [ $? -eq 0 ]
+docker images |grep $imagename > /dev/null
+if [ $? -ne 0 ]
 then
-  docker container restart $containername
-  docker attach $containername
-else
-  echo "Adding new container $containername!"
-  docker run -d --name $containername -e DISPLAY=host.docker.internal:0 -v /private/tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/root -it alpine /bin/bash
+  echo ""
+  echo "Building new image $imagename"
+  echo "---"
+
+  cat > $dfile << _EOF_
+FROM alpine:latest
+RUN apk update && apk add $app
+WORKDIR /root
+_EOF_
+  docker build -t $imagename $dfiledir
+
+  if [ $? -ne 0 ]
+  then
+    echo "Failed to build docker container!"
+    exit 2
+  fi
+  rm -rf $dfiledir
 fi
+
+docker run -d --name $containername -e DISPLAY=host.docker.internal:0 -v /private/tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/root -it alpine $app $arguments
+docker container rm $containername
